version: '3.6'
services:
  pl_crawl_postgres:
    container_name: pl_crawl_postgres
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pl_crawl_db
      PGDATA: /pgdata
    ports:
      - 5434:5432
    volumes:
      - ./db_data:/pgdata
volumes:
  db_data:

